### ISSUE TITLE
Crash server when copy/past "<>"

### ISSUE THREAD

**Issue by zbdm** [Qirky/Troop#16]
Big issue when copy/paste a line containing <> ex: `a1 >> play("<x >< :>")` ,
The server crash and I get this error :  

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\sebas\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\sebas\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sebas\Troop\src\receiver.py", line 91, in handle
    raise(e)
  File "C:\Users\sebas\Troop\src\receiver.py", line 69, in handle
    packet = self.reader.feed(self.sock.recv(self.bytes))
  File "C:\Users\sebas\Troop\src\message.py", line 34, in feed
    raise EmptyMessageError()
src.message.EmptyMessageError: 'Message contained no data'`

**Comment by Qirky** [comment]
Thanks for the catch! Can you update to the latest version and see if the latest update fixes this for you?

**Comment by zbdm** [comment]
Thank you so much, it seems repaired with the last update. This happened to us last Saturday night during a show and it was a little annoying.
