### ISSUE TITLE
backspace doesn't work properly

### ISSUE THREAD

**Issue by hyansuper** [Qirky/Troop#18]
When I hit Backspace, things start to go wrong.
1. Text is not deleted from where the cursor is, but from the end of the line
2. After deleting some text by hitting Backspace, when I type as normal, thosed deleted text apears again
3.Delete key does not work
below is the error message from server ternimal:

` python3 run-server.py 
Password (leave blank for no password): 
Server running @ 192.168.1.90 on port 57890

New connected user 'ad' from 127.0.0.1
p>>play() [9, -1]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hyan/Troop/src/server.py", line 368, in update_send
    msg = self.handle_operation(msg)
  File "/home/hyan/Troop/src/server.py", line 221, in handle_operation
    raise err
  File "/home/hyan/Troop/src/server.py", line 214, in handle_operation
    op = self.receive_operation(message["src_id"], message["revision"], TextOperation(message["operation"]))
  File "/home/hyan/Troop/src/ot/server.py", line 49, in receive_operation
    self.document = operation(self.document)
  File "/home/hyan/Troop/src/ot/text_operation.py", line 143, in __call__
    raise IncompatibleOperationError("Cannot apply operation: operation is too long.")
src.ot.text_operation.IncompatibleOperationError: Cannot apply operation: operation is too long.`

**Comment by Qirky** [comment]
Ahh thanks for letting me know - really stupid error that accidentally ignored deletes on the client side thus giving you that error message. Fixed now!
