### ISSUE TITLE
cannot import name windll on Mac

### ISSUE THREAD

**Issue by Chovin** [Qirky/Troop#3]
https://github.com/Qirky/Troop/commit/560788dbc3949e635df6363fc347638a510316e8
introduces an error on startup for Mac
```py
Traceback (most recent call last):
  File "run-client.py", line 24, in <module>
    from src.client import Client
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/client.py", line 3, in <module>
    from .interface import *
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/interface/__init__.py", line 2, in <module>
    from .interface import *
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/interface/interface.py", line 3, in <module>
    from ..config import *
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/config.py", line 8, in <module>
    from ctypes import windll
ImportError: cannot import name windll
```

**Comment by Qirky** [comment]
This has been fixed - woops!
