### ISSUE TITLE
Unable to save/open files

### ISSUE THREAD

**Issue by hellocatfood** [Qirky/Troop#34]
If I go to File > Save nothing happens (no window and no messages in the terminal).

If I press Ctrl + S or Ctrl + O I get the follow terminal error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1550, in __call__
    return self.func(*args)
  File "/home/hellocatfood/Desktop/Troop/src/interface/menu_bar.py", line 109, in save_file
    lang_files = ("{} file".format(repr(self.root.lang)), self.root.lang.filetype )
  File "/home/hellocatfood/Desktop/Troop/src/interpreter.py", line 73, in __repr__
    return self.name if name is not None else repr(self.__class__.__name__)
NameError: global name 'name' is not defined
```

**Comment by Qirky** [comment]
Woops! That should be sorted now
