### ISSUE TITLE
starting client with "-i -m none" kills other clients

### ISSUE THREAD

**Issue by jwaldmann** [Qirky/Troop#52]
I have a server running, and one client with mode tidalcycles. When I try to join another client (with mode none), the following happens, and the first client dies (since the server disconnects it? I have to look again. For now, I'm just happy that it seems to work without "-i")
```
python run-client.py  -H XX.XX.XX.XX -P XX -m none -i
Enter a name: XX
Password: XX
Password accepted
...
Traceback (most recent call last):
  File "run-client.py", line 131, in <module>
    myClient = Client(**options)
  File "/home/waldmann/software/music/Troop/src/client.py", line 37, in __init__
    self.input.start()
  File "/home/waldmann/software/music/Troop/src/interface/conn_info.py", line 100, in start
    self.finish()
  File "/home/waldmann/software/music/Troop/src/interface/conn_info.py", line 117, in finish
    self.client.setup(**self.options)
  File "/home/waldmann/software/music/Troop/src/client.py", line 107, in setup
    self.lang = langtypes[lang](self, self.args, syntax=getInterpreter(syntax))
  File "/home/waldmann/software/music/Troop/src/config.py", line 135, in getInterpreter
    return langnames.get(path.lower(), path)
AttributeError: 'int' object has no attribute 'lower'
```

**Comment by Qirky** [comment]
Good spot - fixed
