### ISSUE TITLE
client hangs after 'Message contained no data'

### ISSUE THREAD

**Issue by jwaldmann** [Qirky/Troop#55]
I often get this in the lower-left client window
```
[Errno 32] Broken pipe
"Can't connect to server"
Warning: connection lost.
```
and at the same time this in the console:
```
Exception in thread Thread-1:                                                [0/831]
Traceback (most recent call last):                                                  
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()                                                                      
  File "/usr/lib64/python3.8/threading.py", line 870, in run         
    self._target(*self._args, **self._kwargs)                                    
  File "/home/waldmann/software/music/Troop/src/receiver.py", line 93, in handle
    raise(e)                                                                        
  File "/home/waldmann/software/music/Troop/src/receiver.py", line 71, in handle    
    packet = self.reader.feed(self.sock.recv(self.bytes))                           
  File "/home/waldmann/software/music/Troop/src/message.py", line 46, in feed       
    raise EmptyMessageError()             
src.message.EmptyMessageError: 'Message contained no data'    
```

**Comment by Qirky** [comment]
Yup it's a bug that happens sometimes when connections drop
