### ISSUE TITLE
--

### ISSUE THREAD

**Issue by ghost** [Qirky/Troop#63]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\vinna\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\vinna\OneDrive\Desktop\qr gen\main.py", line 93, in generate
    self.qr_code.config(Image=self.im)
  File "C:\Users\vinna\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\vinna\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-Image"

**Comment by Qirky** [comment]
Hi @siddu2003, I'm not sure if this error is related to the Troop program - could you provide a bit more information about what you did/what caused the error?

**Comment by ghost** [comment]
@Qirky hey, I was doing a GUI project on python, which generates a QR code on the details provided. after running the program I faced this issue.

**Comment by Qirky** [comment]
Are you using the Troop GUI for any of this? If not, I can't help you unfortunately. Maybe stackoverflow might be a good place to look? You should also provide the code you've written - it might just be that you need to use lower case 'i' for `qr_code.config(image=...)` but providing your code will help people debug with you. If this isn't related specifically to Troop, I'll have to close the issue

**Comment by ghost** [comment]
@Qirky  oh I'm using Tkinter for this one, thanks for the suggestion and for responding
