### ISSUE TITLE
Transparency doesn't work on Mac

### ISSUE THREAD

**Issue by Chovin** [Qirky/Troop#7]
When trying to turn on transparency:

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/Users/Chovin/Projects/LiveCoding/Troop/src/interface/interface.py", line 1174, in ToggleTransparency
    self.root.wm_attributes('-transparentcolor', alpha)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1619, in wm_attributes
    return self.tk.call(args)
TclError: bad attribute "-transparentcolor": must be -alpha, -fullscreen, -modified, -notify, -titlepath, -topmost, or -transparent
```

this seems to be a Windows only feature https://www.tcl.tk/man/tcl8.4/TkCmd/wm.htm#M13
:(

although it does seem there might be a Mac alternative: https://stackoverflow.com/a/44296157

**Comment by Qirky** [comment]
I've added in the Mac OS alternative but it can cause some visual tearing at times. If you could test it out and let me know that would be great.

**Comment by Chovin** [comment]
yeah, #8 still causes tearing, as it seems its history has diverged, would you like me to close it and move my future findings here?

**Comment by Qirky** [comment]
Oh yeah, sorry about that - I hadn't realised there was a PR and added it in myself.

**Comment by Chovin** [comment]
will do. I'll update here when I get time to look into it more
